AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Role: !GetAtt MyLambdaRole.Arn

  FileUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: file-upload-function/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Role: !GetAtt MyLambdaRole.Arn

  MyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MyLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: arn:aws:s3:::resume-classifier/*

  ApiGatewayApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: '2.0'
        info:
          title: File Upload API
        paths:
          /upload:
            post:
              consumes:
                - multipart/form-data
              produces:
                - application/json
              parameters:
                - in: formData
                  name: file
                  type: file
                  required: true
              responses:
                '200':
                  description: File upload successful
                  schema:
                    type: object
              x-amazon-apigateway-integration:
                type: aws_proxy
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FileUploadFunction.Arn}/invocations
                httpMethod: POST
                responses:
                  default:
                    statusCode: '200'
